// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/cpartogi/warteg/schema/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/cpartogi/warteg/schema/response"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// WartegAdd provides a mock function with given fields: ctx, addw
func (_m *Repository) WartegAdd(ctx context.Context, addw request.Warteg) (response.WartegAdd, error) {
	ret := _m.Called(ctx, addw)

	var r0 response.WartegAdd
	if rf, ok := ret.Get(0).(func(context.Context, request.Warteg) response.WartegAdd); ok {
		r0 = rf(ctx, addw)
	} else {
		r0 = ret.Get(0).(response.WartegAdd)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.Warteg) error); ok {
		r1 = rf(ctx, addw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WartegDelete provides a mock function with given fields: ctx, warteg_id
func (_m *Repository) WartegDelete(ctx context.Context, warteg_id string) (response.WartegDelete, error) {
	ret := _m.Called(ctx, warteg_id)

	var r0 response.WartegDelete
	if rf, ok := ret.Get(0).(func(context.Context, string) response.WartegDelete); ok {
		r0 = rf(ctx, warteg_id)
	} else {
		r0 = ret.Get(0).(response.WartegDelete)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, warteg_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WartegDetail provides a mock function with given fields: ctx, warteg_id
func (_m *Repository) WartegDetail(ctx context.Context, warteg_id string) (response.WartegDetail, error) {
	ret := _m.Called(ctx, warteg_id)

	var r0 response.WartegDetail
	if rf, ok := ret.Get(0).(func(context.Context, string) response.WartegDetail); ok {
		r0 = rf(ctx, warteg_id)
	} else {
		r0 = ret.Get(0).(response.WartegDetail)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, warteg_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WartegList provides a mock function with given fields: ctx, warteg_name
func (_m *Repository) WartegList(ctx context.Context, warteg_name string) ([]response.WartegList, error) {
	ret := _m.Called(ctx, warteg_name)

	var r0 []response.WartegList
	if rf, ok := ret.Get(0).(func(context.Context, string) []response.WartegList); ok {
		r0 = rf(ctx, warteg_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.WartegList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, warteg_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WartegUpdate provides a mock function with given fields: ctx, warteg_id, uwt
func (_m *Repository) WartegUpdate(ctx context.Context, warteg_id string, uwt request.WartegUpdate) (response.WartegUpdate, error) {
	ret := _m.Called(ctx, warteg_id, uwt)

	var r0 response.WartegUpdate
	if rf, ok := ret.Get(0).(func(context.Context, string, request.WartegUpdate) response.WartegUpdate); ok {
		r0 = rf(ctx, warteg_id, uwt)
	} else {
		r0 = ret.Get(0).(response.WartegUpdate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, request.WartegUpdate) error); ok {
		r1 = rf(ctx, warteg_id, uwt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
