api:
  port: ":7200"
  timeout: 1000
auth:
  private_key: "privatekey"
  expire: "+30m"
database:
    mysql: 
      host: "localhost"
      port: "3306"
      dbname: "warteg"
      user: "root"
      password: "root"
      sslmode: ""
context:
  timeout: 2